### ISSUE TITLE
No Actual Source Code

### ISSUE THREAD

**Issue by trav0r** [Monoprice3DP/MP10Firmware72#1]
I'm interested in knowing which features and settings have been enabled in this custom build of Marlin. 

Also I want to play with linear acceleration. I'd be willing to accept full responsibility for supporting non official firmware.

**Comment by alexsie48** [comment]
Are there any updates on the status of this?

**Comment by Buszkiewicz** [comment]
I dont know what you mean sorryGesendet mit der WEB.DE Mail AppAm 10.07.20 um 07:52 schrieb Alex Siegel
                
            
            
                
                    Von: "Alex Siegel" <notifications@github.com>Datum: 10. Juli 2020An: "Monoprice3DP/MP10Firmware72" <MP10Firmware72@noreply.github.com>Cc: "Subscribed" <subscribed@noreply.github.com>Betreff: Re: [Monoprice3DP/MP10Firmware72] No Actual Source Code (#1)
                
                
Are there any updates on the status of this?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Monoprice3DP/MP10Firmware72/issues/1#issuecomment-656497251",
"url": "https://github.com/Monoprice3DP/MP10Firmware72/issues/1#issuecomment-656497251",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by trav0r** [comment]
The file included in this repository is just the compiled firmware and not the code used to build the firmware. 

Example: [Marlin Firmware for Ender 3](https://github.com/Creality3DPrinting/Ender-3/tree/master/Ender-3%20Firmware%20(Marlin))

**Comment by trav0r** [comment]
Any chance of Monoprice uploading the source for the firmware? I'd really like to see what settings are enabled for the MP10.

**Comment by trav0r** [comment]
I just saw that there's a new repo for the source. I'll go complain there about the lack of source code.

**Comment by ChaseCorp** [comment]
Hey so i reached out to monoprice and just flat out asked for the all the files. I have the firmware (not compiled) posted here https://github.com/ChaseCorp/Monoprice-MP10-source 

hope it helps
